### ISSUE TITLE
Disable Hotkeys using the Override file?

### ISSUE THREAD

**Issue by mrweaver** [DreymaR/BigBagKbdTrixPKL#27]
Hi, thanks very much for your work on this tool, its great!

Is it possible to disable the hotkeys using the `EPKL_Settings_Override` file? I am aware that I can comment them out in the default file, but it is handy to know that when an update comes out, I can just preserve the override files for my settings.

Cheers,
Michael.

**Comment by DreymaR** [comment]
Excellent question!

Commenting out a setting in an Override file means you'll drop through to the Default so that won't disable anything. I see your problem. I haven't implemented any specific ways of disabling a hotkey in the Override file, but I found a sneaky trick:

You can set any hotkey you don't want around to `Sleep` – or, if you actually need that key, another one you don't use such as `Break` or `Pause`. There's a list of key names on the AHK help pages. It's possible to set any combination of hotkeys to the same key this way – the key name will show up in the menu but that shouldn't be much of a problem.

Hope that solution is satisfactory!

**Comment by mrweaver** [comment]
That's great. Thanks! I had a bit of a look through the AHK documentation but didn't come across an solution. `Sleep` is what I was looking for though!

Another thought, would it make sense to have a hotkey (e.g. `Break` or `Pause`) that could be used to enable/disable all other hotkeys? In my case, I usually leave the EPKL hotkeys as default until they conflict with other software. Being able to disable all EPKL hotkeys could of use, perhaps?

I'm not trying to create work for you though! I appreciate all your efforts @DreymaR, many thanks!

**Comment by DreymaR** [comment]
By "all EPKL hotkeys", do you mean all hotkeys except key mapping hotkeys? If not, the Suspend hotkey takes care of disabling all hotkeys. As for including a hotkey to disable the special hotkeys... I don't think that's useful enough to warrant the added complexity.

I will consider adding an option to map a hotkey to `--` to disable it, to avoid this `Sleep` trickery.

**Comment by mrweaver** [comment]
Yep, I meant hotkeys with the exception the mapping keys.  

Cool, that sounds great! Thanks for your help :)
