### ISSUE TITLE
My numpad doesn't really work with EPKL

### ISSUE THREAD

**Issue by attuanmtrinh** [DreymaR/BigBagKbdTrixPKL#28]
I use a 89-key keyboard with the numpad also works as the Home/End/etc keys. Using EPKL everything works fine except the numpad works regardless of the NumLock state, and the navigation keys doesn't work at all. I just started using EPKL so I don't really know what to do. Any suggestions would really be appreciated.

**Comment by DreymaR** [comment]
Not sure why that'd be, as EPKL doesn't remap the NumPad keys (QWP_1 etc) apart from the decimal key QWPDC. The nav keys may be remapped, as seen in the [EPKL_Layouts_Default.ini](https://github.com/DreymaR/BigBagKbdTrixPKL/blob/99d12af11b16822217d7f67531a66750c0b3edb7/EPKL_Layouts_Default.ini#L170-L173) file, but they aren't by default.

Try selecting AHK Key History on the EPKL menu and play around with it a little to see if you learn something (F5 refreshes).

**Comment by guraltsev** [comment]
Hello! I think I found a temporary solution. The problem is not that the NumPad keys are remapped but rather that the non-numpad keys (`Home` etc) are remapped to the numpad ones and that for some strange reason causes problems. 

Take a look here at a temporary workaround:
https://github.com/DreymaR/BigBagKbdTrixPKL/issues/46#issuecomment-1200343064

**Comment by DreymaR** [comment]
This probably stems from the weird way the Virtual Key codes of the nav keys on the NumPad are treated by AutoHotkey.

Since the Home etc keys are VK mapped in EPKL, pressing the NumPad Home must be intercepted by AHK as a Home key event which then got mapped by EPKL to NumPad Home – but that somehow didn't work as expected.

Hopefully, 22af93a fixes it? I don't have a NumPad on my laptop to test it. Please let me know.
