### ISSUE TITLE
v1.4 broke my ø mapping

### ISSUE THREAD

**Issue by bnm12** [DreymaR/BigBagKbdTrixPKL#57]
I don't know if I need to make any changes moving to v1.4 but I couldn't find any information on the releases page or on the Colemak forums. I moved over my override files from v1.3.1 so maybe that's it? 
I use the CurlAWideSym(ISO) variant and access ø using AltGr + (qwerty b)
With v1.4 I instead get just an empty space or otherwise unprintable char, and sometimes I weirdly get `{¤}`

EDIT: on further testing it seems to repeat my last pressed button and `{¤}` represents backspace sometimes?

**Comment by DreymaR** [comment]
For non-layout key settings, look in the EPKL_Layouts.ini file. In this case, it looks as if your variant doesn't set the ISO key (which is on QWERTY B using the ISO Angle mod), and the default is a Repeat key. Look in the Big Bag for info about Compose and Repeat, and in the EPKL README.

You can easily override this, either by editing in one of the override files or by using the Key Mapper GUI.

The weird `{¤}` bug has been fixed in the latest commits.

**Comment by bnm12** [comment]
Any reason why this would have changed from v1.3.1 using the same config files?

**Comment by DreymaR** [comment]
I don't remember 100% but I did remove some ISO key mappings from layouts so as to leave the default setting to the EPKL_Layouts file. That could be it.

Help images aren't automatically updated. You can generate new images using the EPKL HIG with Inkscape.

**Comment by bnm12** [comment]
I've been doing some digging and I guess it has to do with this change? https://github.com/DreymaR/BigBagKbdTrixPKL/compare/EPKL_1-3-1...EPKL_1-4-0#diff-eb141f55ff551b54786f5214366e164f0111a824a56a8d7939e3b2e5c9e3bb5cR280-R311

This image doesn't seem to reflect the new behavior though https://github.com/DreymaR/BigBagKbdTrixPKL/blob/master/Layouts/Colemak/Cmk-eD/Cmk-eD_ISO_CurlAWideSym/state6.png

Sorry for being a pain but I really don't understand all the fine details of how all these config files play together and the AHK syntax etc. I don't really deal much with keyboards and keycodes, I just like Colemak CAWS and want to use it like I've gotten used to my å and æ are still there with AltGr, so it feels weird for me to have to type something like o/ + compose to get ø.

What do I need to put in my override to restore the ø instead of the repeat on AltGr+compose (ISO b)

I don't really understand the concept of the CoDeKey it sounds like the new cool thing but I have not found the documentation very helpful for
a) How to set it up
b) What it does

My main pain is just that the å and æ are accessible but ø no longer is. I guess I could switch to the DkNo locale version, but I like the location of [] and {} as a software dev quite well and I type english quite a lot of the time so when I type in danish it's not too big of a deal to have to hit a button to get the letters

**Comment by DreymaR** [comment]
I told you that help images aren't automatically updated. I saw no reason to update that image, as it's up to the user what to use that key for. A symbol like Œ or Ø is as good as any there.

On my setup though, AltGr plus the ISO key actually gives Ø. In the EPKL_Layouts_Override.ini file, I have:
`QW_LG = vc_LG   	4   	®®  	®4  	--  	ø   	Ø`
This makes the ISO key a Repeat key on the normal state, and ø on AltGr. You can make mappings like that using the KeyMapper menu (from the Layout/Settings menu choice).

**Comment by DreymaR** [comment]
All you have to do to make that Def Compose key work as CoDeKey, is specify that Def is a CoDeKey in your Settings_Override file. You can do it on the Special Keys tab of the Settings GUI too.

**Comment by DreymaR** [comment]
Oh, I see. That's in the Big Bag which describes my tricks; it does not go into depth regarding how to implement them for each platform. That info is left for the platform implementations themselves. Were you under the impression that the Big Bag is an EPKL-specific site? If you activate one of the non-Windows platform icons it'll show some info on the other implementations. That's still far from comprehensive, I'm afraid.

If I made that table contain EPKL syntax, it'd be confusing for people wanting to make a CoDeKey with QMK or on some other platform. I can't do that. Such info must be in the EPKL repo, in readme files and code comments.

Since the CoDeKey is a dead key functionality, in the case of EPKL its mappings are in the deadkey file. Did you find it?
https://github.com/DreymaR/BigBagKbdTrixPKL/blob/f2f1f1ef4221db88ab45dcbbbc4033b916148cdc/Files/_eD_DeadKeys.ini#L60-L145
