### ISSUE TITLE
ctrl+shift+3 doesn't suspend EPKL

### ISSUE THREAD

**Issue by ChenFryd** [DreymaR/BigBagKbdTrixPKL#72]
It seems like it doesn't matter which mode I'm in, it doesn't suspend the program. (right clicking and then selecting suspend does suspend the program)

**Comment by DreymaR** [comment]
This is a known issue, I'm afraid. It seems to work after EPKL has been suspended once, but not before that. Not sure if it's a Windows peculiarity, an AHK bug, or what. Other shortcuts don't behave in this odd way.

The workaround I use is to use the synonym shortcut `Ctrl+Shift+Backtick` (on the Tilde key) instead. That works all the time for me. It's a bit less logical since all the other EPKL shortcuts use numbers, but it's the best I could think of.

Not sure what I could do to remedy the problem.
