### ISSUE TITLE
Cmk-CkAW-_@K is not wide

### ISSUE THREAD

**Issue by laMudri** [DreymaR/BigBagKbdTrixPKL#76]
Starting with the layout specified in `./Layouts/Colemak/Cmk-eD/Cmk-eD_ISO_CurlAWide/Layout.ini`, I adapted the instructions given in https://forum.colemak.com/topic/2955-customizing-epkl-cmkedisocurlawidesym/#p25013 to the non-sym variant. I added a `k` between the `C` and `A` in [line 31](https://github.com/DreymaR/BigBagKbdTrixPKL/blob/master/Layouts/Colemak/Cmk-eD/Cmk-eD_ISO_CurlAWide/Layout.ini#L31C19-L31C30), and nothing else. However, despite the name, the layout this produced was non-wide – i.e, the key labelled `J` produced an `n`, where I would expect a `k`. I tried to find out why this would be, but I got lost in all the remap definitions.

**Comment by DreymaR** [comment]
Yes, remap definitions can get complex. Sorry about that!

The `Cmk-CkAW_@K` remap should work exactly like the `Cmk-CAW-_@K` one, except with DHk instead of the standard DHm. And to me it looks as if you did it right. Well, almost. Due to a minor syntax error, you got no working remap at all and ended up with vanilla Colemak.

Turns out I had omitted the hyphen after AW for the CkAW(-) one. That hyphen means no Sym mod, so it ought to be there. I've pushed a fix commit just now. Either update and recompile your EPKL.exe, or re-edit your file so it's `Cmk-CkAW_` not `Cmk-CkAW-_`.

It's easy to miss a hyphen, of course. But after the fix, the naming should be consistent.

Note that you can now make and edit a `Layout_Override.ini` file instead of the original `Layout.ini` file. You could add just your remap change there, under a `[pkl]` section. That way, you keep your edits clean and visible, and it'll be robust towards any future updates I make to the Layout.ini file.
