### ISSUE TITLE
Key beside RShift in ABNT2 Keyboard

### ISSUE THREAD

**Issue by QPOZP** [DreymaR/BigBagKbdTrixPKL#9]
The standard [ABNT2 keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Brazilian_107-key_ABNT2_Windows_keyboard.jpg/1920px-Brazilian_107-key_ABNT2_Windows_keyboard.jpg) has a key beside the RShift key which isn't remapped into anything, so you end up with two keys which does the same thing.

- How would one go about remapping it to RShift?
- Do you pretend to do anything about it?

**Comment by DreymaR** [comment]
I haven't done anything about it yet, because nobody asked. But I'll include it in my next commit if you help me find its scan code (SC) and virtual key code (VK). I think the special key may have SC073, but I'm not sure. If you select "AHK Key history..." on the EPKL menu you get a window where if you press that key and then F5 you'll see what its VK and SC are (it'll show up as a "h" key press down/up near the bottom of the window). Can you tell me what the first two entries are?

**Comment by QPOZP** [comment]
Thank you, I edited the baselayout and it worked, except once I press a letter key it resets to lowercase and I have to press it again to capitalize another letter, I can't just keep it pressed.
Here is the AHK output:
```
VK  SC	Type	Up/Dn	Elapsed	Key
-----------------------------------
C1  073	 	d	10.20	/          
C1  073	 	u	0.05	/          
```

**Comment by DreymaR** [comment]
I've reproduced this behavior mapping another key to a Shift modifier. It's a kind of problem for EPKL, somehow it works when mapping a modifier key but not a non-modifier key to a modifier. I'll try to look into it. For now, you can map the key to anything else at least I hope?

**Comment by QPOZP** [comment]
Thank you, I'll just disable the key until I possibly figure something else to do with it.
